import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'
import BlogCard from '../components/BlogCard'

const graphcms = new GraphQLClient(
  "https://api-ap-southeast-2.graphcms.com/v2/cl3zwq5zt1pfp01xs7tja9q9t/master"
); 

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        username
        avatar {
          url 
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

// This will be run at build time. So it will fetch external data and pre-render the content 
export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  return {
    props:{
      posts,
    },
  };
}

export default function Home({posts}) {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {posts.map((post) => (
            <BlogCard 
            title={post.title} 
            author={post.author} 
            coverPhoto={post.coverPhoto} 
            key={post.id} 
            datePublished={post.datePublished} 
            slug={post.slug} 
            />
          ))}
        </div>
      </main>

    </div>
  )
}
